### ISSUE TITLE
Make serial_no unique case-insensitively

### ISSUE THREAD

**Issue by shaneallgeier** [mostateresnet/rimproject#86]
Now that `serial_no` is unique, I would like to make it case-insensitively unique. So that you can't insert an equipment with `serial_no='49G2NFF6'` if `serial_no='49g2nff6'` is already in the database. Also make sure that the new API still updates the same Equipment regardless of whether you pass in  `49G2NFF6` or `49g2nff6`.

**Comment by shaneallgeier** [comment]
Ideally this would be on the model itself and that would fix it everywhere. But if that's not possible/sufficient then we'll just have to implement this individually in each view I guess. And also in the Django admin.

**Comment by jayanth-madupalli** [comment]
Created a new pull request for this. Now, we'll be converting serial_no to uppercase while inserting and also while comparing/serializing through API. Effectively, making it case-insensitive.
